# Analysis options for music_theory
# See PROJECT_CONSTITUTION.md for rationale
#
# Extends package:lints/recommended.yaml with stricter rules
# for a pub.dev quality package.

include: package:lints/recommended.yaml

analyzer:
  exclude:
    - build/**
    - "**.g.dart"
    - "**.mocks.dart"
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    # Treat these as errors in CI
    missing_return: error
    missing_required_param: error
    dead_code: warning
    # Allow print in CLI/examples (expected for CLI tools)
    avoid_print: ignore

linter:
  rules:
    # ============================================
    # Error Prevention
    # ============================================
    - avoid_print  # Enabled but ignored via analyzer (allows per-file override)
    - avoid_dynamic_calls
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - throw_in_finally
    - unnecessary_statements
    - avoid_type_to_string
    - no_duplicate_case_values
    - valid_regexps

    # ============================================
    # Style & Clarity
    # ============================================
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_single_quotes
    - avoid_unused_constructor_parameters
    - avoid_redundant_argument_values
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_string_interpolations
    - use_string_buffers

    # ============================================
    # Documentation (for pub.dev points)
    # ============================================
    - public_member_api_docs

    # ============================================
    # Type Safety
    # ============================================
    - avoid_init_to_null
    - prefer_typing_uninitialized_variables
    - type_annotate_public_apis

    # ============================================
    # Null Safety
    # ============================================
    - avoid_null_checks_in_equality_operators
    - cast_nullable_to_non_nullable
    - null_check_on_nullable_type_parameter
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations

    # ============================================
    # Collections
    # ============================================
    - prefer_collection_literals
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_elements_to_conditional_expressions
    - prefer_spread_collections
    - unnecessary_to_list_in_spreads

    # ============================================
    # Async
    # ============================================
    - await_only_futures
    - unawaited_futures

    # ============================================
    # Security-adjacent
    # ============================================
    - avoid_web_libraries_in_flutter
    - secure_pubspec_urls
